"""create vehicles and drivers tables

Revision ID: fb6e5d6fe752
Revises: 3c35dd81008f
Create Date: 2026-07-12 13:42:14.418396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb6e5d6fe752'
down_revision: Union[str, Sequence[str], None] = '3c35dd81008f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('license_number', sa.String(length=30), nullable=False),
    sa.Column('license_category', sa.Enum('A', 'B', 'C', 'D', 'E', 'CE', 'DE', name='licensecategoryenum'), nullable=False),
    sa.Column('license_expiry', sa.Date(), nullable=False),
    sa.Column('contact_number', sa.String(length=20), nullable=False),
    sa.Column('safety_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.Enum('available', 'on_trip', 'off_duty', 'suspended', name='driverstatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('safety_score >= 0 AND safety_score <= 100', name='check_driver_safety_score_bounds'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_id'), 'drivers', ['id'], unique=False)
    op.create_index(op.f('ix_drivers_license_number'), 'drivers', ['license_number'], unique=True)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('truck', 'van', 'bus', 'sedan', 'pickup', 'other', name='vehicletypeenum'), nullable=False),
    sa.Column('max_load_capacity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('odometer', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('acquisition_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('available', 'on_trip', 'in_shop', 'retired', name='vehiclestatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('acquisition_cost >= 0', name='check_vehicle_acquisition_cost_non_negative'),
    sa.CheckConstraint('max_load_capacity > 0', name='check_vehicle_max_load_capacity_positive'),
    sa.CheckConstraint('odometer >= 0', name='check_vehicle_odometer_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_registration_number'), 'vehicles', ['registration_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_registration_number'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_drivers_license_number'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_id'), table_name='drivers')
    op.drop_table('drivers')
    # ### end Alembic commands ###
